### ISSUE TITLE
Formatting not working, shows message to see issues.

### ISSUE THREAD

**Issue by deepak-atariya-teri** [shufo/vscode-blade-formatter#14] opened 2020-11-06 09:03 UTC
## Steps to Reproduce

1.
2.
3.
4.

**Comment by shufo** [comment] 2020-11-06 18:03
@deepak-atariya-teri 
Could you provide your environment and reproduce procedure? Thanks.

**Comment by prettifystudio** [comment] 2020-11-10 13:57
Hello, I think it doesn't work with Blade Components. I tried using it on a blade file that uses Blade Components, it doesn't work. However, using it on a "plain" blade file does the job.

**Comment by shufo** [comment] 2020-11-11 05:38
@prettifystudio 
Could you provide example template source?
Currently custom component defined in Laravel 6.x are not supported.

Components in 7.x, 8.x like below are supported
 
```php
@section('foo')
    <x-alert />
    <x-user-profile />
    <x-inputs.button />
@endsection
```

**Comment by prettifystudio** [comment] 2020-11-13 08:48
Laravel 8.x 
```
@push('scripts')
    <script>
      console.log('foo');
    </script>
@endpush
<x-app-layout title="Add new client">
    <section class="section">
    </section>
</x-app-layout>
```
Just a notice, the files that give me the error are the files where I'm using displaying data " {{ }} "
 Other files are working okay. I guess it's because of  " {{ }} "

**Comment by shufo** [comment] 2020-11-13 10:38
hm...curly braces without content like `{{ }}` occurs error but if there are something in it `{{ $a }}` worked as expected. 
Thanks! I'll try figure out what causes this error.

**Comment by shufo** [comment] 2021-01-13 13:48
Fixed in v0.6.4

**Closed by shufo** 2021-01-13 13:48 UTC
Labels: bug
